apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

resources:
  - namespace.yaml
  - pvc.yaml
  - ui-pvc.yaml
  - ui-secret.enc.yaml
  - deployment.yaml
  - service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - ingress.yaml
  - searxng-secret.enc.yaml
  - searxng-config.yaml
  - searxng-deployment.yaml
  - searxng-service.yaml
  - searxng-ingress.yaml

