apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sync.yaml
  - namespace.yaml
  - db-secret.enc.yaml
  # - postgresql.yaml
  - pvc.yaml
  - pvc-bigboi.yaml
  # - helmrelease.yaml  # Commented out - migrated to components/immich/overlays/prod
  - ingress.yaml