apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Development environments
  - immich/sync-dev.yaml
  - immich/sync-staging.yaml
  - karakeep/sync-dev.yaml
  - argocd/sync-dev.yaml
  # - argocd/sync-prod.yaml
