apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sync.yaml
  - namespace.yaml
  - db-secret.enc.yaml
  - postgresql.yaml
  - pvc-bigboi.yaml
  - pv.yaml
  - helmrelease.yaml
  - ingress.yaml
  - redis.yaml