apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sync.yaml
  - namespace.yaml
  - db-secret.enc.yaml
  - postgresql.yaml
  - pvc-bigboi.yaml
  - pv.yaml
  - helmrelease.yaml
  - ingress.yaml
  - redis.yaml

# Override image tags for all Immich components
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.119.0
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.119.0