resources:
  - nginx-ingress-helmrelease.yaml
  - local-path-provisioner.yaml
  - bigboi-storage.yaml
  - gateway-api-crds.yaml
  - cilium-gateway.yaml
  - metallb.yaml
  - ip-address-pool.yaml
  - nvidia-device-plugin.yaml