apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich

# Note: karakeep/chart/ is a Helm chart directory (not K8s resources)
# It's referenced by components/karakeep HelmRelease

