apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich-staging

resources:
  - ../../base
  - namespace.yaml
  - helmrelease.yaml
  - db-secret.enc.yaml
  - pvc-postgresql.yaml
  - pvc-bigboi.yaml
  - ingress.yaml
  - redis.yaml
  - postgresql-service-patch.yaml

patches:
  - path: postgresql-resources-patch.yaml

